### PR TITLE
fix task 3

### PR DESCRIPTION
**Pull request by isaev-co**

### CODE REVIEW

**Review by Konstantin1996 — COMMENTED** [review]
Where is the task-4?

**Comment by numatay** [comment]
Hi @Matthew-Risedale ,
I cannot find any relevant files for task 04. Ping me when you get finished with it.

**Comment by Emerkof** [comment]
@Matthew-Risedale No changes corresponding to `task-4` found. Please, provide link to a branch with appropriate code.

**Comment by isaev-co** [comment]
@numatay @Emerkof sorry for delay, my PR is here https://github.com/Matthew-Risedale/vinyl-store-be/pull/3
hope youll find a time to check my work after deadline 🤞

**Comment by numatay** [comment]
Cross-check review results:
- [ ] TASK 4.1 is implemented. (Database, table creation scripts are provided). 
- [ ] TASK 4.2 is implemented lambda links are provided and returns data
- [ ] TASK 4.3 is implemented lambda links are provided and products is stored in DB
- [ ]  Frontend application is integrated with product service (/products API) and products from product-service are represented on Frontend.
- [ ] +1 - POST/products lambda functions returns error 400 status code if product data is invalid ()
- [ ] +1 - All lambdas return error 500 status code on any error (DB connection, any unhandled error in code)
- [ ] +1 - All lambdas do console.log for each incoming requests and their arguments
- [ ] +1 - Transaction based creation of product 

**Points earned**:  _x_ pts

**Pull request merged**
